AWSTemplateFormatVersion: "2010-09-09"
Description: Monitoring stack

Parameters:
  LambdaFunctionName:
    Type: String
    Description: Name of the Lambda function to monitor

Resources:
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: cloud-resume-alerts

  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${LambdaFunctionName}-Errors-Alarm"
      AlarmDescription: Alarm when Lambda function reports errors
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching