AWSTemplateFormatVersion: "2010-09-09"
Description: Monitoring stack

Parameters:
  LambdaFunctionToMonitor:
    Type: String
  ArtifactBucketName:
    Type: String
  ArtifactKey:
    Type: String

Resources:
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: cloud-resume-alerts

  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${LambdaFunctionToMonitor}-Errors-Alarm"
      AlarmDescription: Alarm when Lambda function reports errors
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionToMonitor
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  LambdaLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${LambdaFunctionToMonitor}-Latency-Alarm"
      AlarmDescription: "Alarm when Lambda p95 duration exceeds 1000 ms"
      Namespace: AWS/Lambda
      MetricName: Duration
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionToMonitor
      ExtendedStatistic: p95
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1000
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching

  LambdaInvocationSpikeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${LambdaFunctionToMonitor}-Invocation-Spike-Alarm"
      AlarmDescription: "Alarm when Lambda invocation count spikes abnormally"
      Namespace: AWS/Lambda
      MetricName: Invocations
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionToMonitor
      Statistic: Sum
      Period: 30
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertTopic
      TreatMissingData: notBreaching


  SlackNotifierLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SlackWebhookSSMRead
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cloud-resume/slack/webhook

              - Effect: Allow
                Action:
                    - kms:Decrypt
                Resource: "*"
                Condition:
                  StringEquals:
                    kms:ViaService: !Sub ssm.${AWS::Region}.amazonaws.com

  SlackNotifierLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SlackNotifierLambda
      Runtime: python3.11
      Handler: slack_notifier.lambda_handler
      Timeout: 10
      Role: !GetAtt SlackNotifierLambdaRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucketName
        S3Key: !Ref ArtifactKey

  SlackNotifierSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertTopic
      Protocol: lambda
      Endpoint: !GetAtt SlackNotifierLambda.Arn

  SlackNotifierLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SlackNotifierLambda
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref AlertTopic
