AWSTemplateFormatVersion: '2010-09-09'
Description: Bucket for storing Lambda & CloudFormation artifacts

Parameters:
  BucketName:
    Type: String
    Description: Name of the artifacts bucket

Resources:
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
