AWSTemplateFormatVersion: '2010-09-09'
Description: Static Site with S3 and CloudFront OAC
    
Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "ivanovv-dev-iac-${AWS::StackName}" 

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${StaticSiteBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn:
                  !Join [ "",
                    [ "arn:aws:cloudfront::", !Ref "AWS::AccountId", ":distribution/", !GetAtt StaticSiteDistribution.Id ]
                  ]
