AWSTemplateFormatVersion: '2010-09-09'
Description: Static Site with S3 and CloudFront OAC
    
Parameters:
  CertificateArn:
    Type: String
    Description: ACM certificate ARN for CloudFront

Resources:

  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "ivanovv-dev-iac" 

  StaticSiteOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: ivanovv-dev-iac-oac
        Description: OAC for static site
        SigningBehavior: always
        SigningProtocol: sigv4
        OriginAccessControlOriginType: s3

  StaticSiteDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: StaticSiteBucket
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt StaticSiteBucket.DomainName
            OriginAccessControlId: !Ref StaticSiteOAC
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
        Aliases: 
          - ivanovv.dev
          - www.ivanovv.dev
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
        HttpVersion: http2
        PriceClass: PriceClass_100

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${StaticSiteBucket.Arn}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${StaticSiteDistribution}"

Outputs:
  StaticSiteBucketName:
    Description: Name of the S3 bucket hosting the static website
    Value: !Ref StaticSiteBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"